--- #YAML:1.0
name:                Pod-Xhtml
version:             1.52_01
abstract:            Generate well-formed XHTML documents from POD format documentation
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Pod::Parser:                   0
    Pod::ParseUtils:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - British Broadcasting Corporation
